### ISSUE TITLE
QIO List of Feature Requests

### ISSUE THREAD

**Issue by TheOwnerOfThis** [mekanism/Mekanism-Feature-Requests#146]
**Describe the feature you'd like**
I would like the QIO to simply fully replace my AE2 ME system.

**Describe alternatives you've considered**
I currently just don't use the QIO system because I love using auto crafting, since it makes big crafting recipes that you do often much simpler.

**Additional context**
(List of features)
- It would be nice for taking blocks in and out of the QIO not feel sluggish (maybe it's just my computer or server but that's just personal experience)
- I understand it's been requested already, but I would love for the QIO dashboard to have an upgrade or variant that has a crafting grid with JEI support.
- Make the QIO use a little power per item transfer whether it's in or out, or if it's done by the player or automatically
- Implement a multiblock structure that is like a computer for the QIO that allows the QIO to have crafting requests. Have blocks within the computer multiblock structure that supply it with power, make it better at a lot of small tasks or better at very few big tasks
- Have some sort of pipes for the QIO that let it transfer the data, I know there is a wireless variant but pipes from Mekanism look cool.
- Have a UI that lets you make recipes where you tell the QIO computer what to supply and what the recipe is supposed to give back.
- Put the encoded recipes in an export port of some sort that is supposed to go into a chest or machine so that that recipe is now available in the QIO dashboard. 
- You will then need to make an import port on the other chest or another side of the machine so the QIO computer can receive the items.
- When you make a crafting request the QIO computer will send the ingredients it's supposed to send and then will wait for the output it's supposed to get (based on what you told it)
- Let all previous recipes compound on one another so if you have enriched alloys already automated, it will craft those for a more complex recipe automatically (for example: an energy tablet)
- Let you set a minimum of some item so the QIO computer will automatically craft you more when you get below a certain amount

**I know this is almost copying AE2 but these features will make the QIO so much better, but tell me your thoughts**

**Comment by TheOwnerOfThis** [comment]
After talking with @Sílfryí Kalsandryn#5837 for a while on the discord server I guess most of everything I've said has been requested to you guys a lot. I guess the purpose of the QIO system is to let you access all your items at any time anywhere which is what is limiting it from having on-demand auto crafting. I hope that the system has two different variants possibly so that the complex auto crafting part could be implemented later on. I think the idea of having a multiblock computer as a separate module that is strictly wired that can be hooked up to the QIO drive thing would possibly allow for the auto crafting to work. This will make it so users do not **have** to auto craft but have the option to do so if they desire.

**Comment by pupnewfster** [comment]
A couple things: firstly on demand auto crafting isn't really planned. It may happen at some point, but the goal of QIO is to be a late game item storage, and at least personally I think the system of stock keeping large amounts of various items you want is more in line with Mekanism's style of automation than on demand crafting. Secondly, I highly doubt cables will ever happen as part of the entire idea behind QIO is it is wireless (using the same sort of technology as the quantum entangloporters, QIO stands for quantum item orchestration). The "crafting grid/terminal" *will* happen in a unique Mekanism style for V10.1, because it is something we recognize is a massive quality of life thing to have but was not something we had time to do for V10 due to how we want it to be done. You can see my progress on this in the v10-updates channel on our discord (those windows will have JEI support, even though they currently do not, beyond being able to identify which window is selected, as they are still relatively WIP).

**Comment by TheOwnerOfThis** [comment]
Okay, and I'm assuming since it's wireless you would be unable to make it draw power. I guess I will mess around with the QIO in single-player for a while to see what I can do. Thanks for the reply!
