### ISSUE TITLE
Filters: specify block ID & integrate it with JEI

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [mekanism/Mekanism-Feature-Requests#149]
**Describe the the feature you'd like**
Add a fifth way to specify a filter: by specifying the ID of the block you're looking for or, more visually, selecting it in the JEI.

Currently there are four ways filters can be set: ItemStack (requires to have the actual item which may be difficult to do), Tag (doesn't work in a very intuitive way, there are things that don't have useful tags), Material (???), Mod ID (rarely useful).

By specifying the ID directly or indirectly, you can bypass the need to have the item in your inventory and when you don't know what tag is applicable for it.

**Describe alternatives you've considered**
N/A

**Comment by pupnewfster** [comment]
This would serve no purpose as it would be identical to the item stack filter. You can already drag from JEI into the ItemStack filters. The only exception to this is for the digital miner's item stack filter as a small balancing act to actually require people to get the  block. If there was a reasonable/sensible way to make it so that they had to find at least one of the thing before using a tag/modid filter we would but there unfortunately is no simple way to do so, but as they are much more broad filters in general it tends to not be accurate enough for people wanting to bypass actually having to find one of a material first.
