### ISSUE TITLE
QIO Exposer

### ISSUE THREAD

**Issue by theLadyStardust** [mekanism/Mekanism-Feature-Requests#151]
Would it be possible to add a block that exposes the inventory of the QIO system whose frequency it's tuned to? As in, have that block act as if it was holding the entire contents of the QIO system. This would be most useful for integrating a QIO system with AE2/Refined Storage, because it would allow you to just slap a storage bus/external storage on it and have access to the QIO. I really like the QIO for storage, it's a unique way of doing it, but the lack of ability to automate the contents of it really hurts. This would be a solution to that.

**Comment by pupnewfster** [comment]
No. The QIO was designed to be very fast and good at handling large amounts of items due to how it caches and keeps track of them; the entire reason we don't expose the contents via an IItemHandler is because it will just be a source for lag, connecting massive inventories to things like RS/AE2 just is a lag switch because there is no good way for them to know if something changed/grab all the items without having to iterate all the contents quite frequently just in case something changed.

If someone who knows java/how to mod wants to do it properly and make an addon to allow for connecting the two by making it so that RS/AE2 can directly interact with the QIO's cache, I would be more than willing to help them/move various parts of the QIO system to our API package so that they can do so in a more stable way.
