### ISSUE TITLE
Solar Smelter

### ISSUE THREAD

**Issue by KhanhPham05** [mekanism/Mekanism-Feature-Requests#163]
**Describe the the feature you'd like**
When Solar Generator + Energized Smelter. Burn item using solar power without using FE Energy 

**Describe alternatives you've considered**
Some things that similar with using solar panel to smelting things

**Comment by pupnewfster** [comment]
Personally I find this highly unlikely to ever actually happen, but I will leave it open for now as one idea I had at one point is potentially making it so that you can install an upgrade in machines to make them have an extra side slot for things like raw fuel to run off of, and if I ever actually end up doing something like this, this idea could be paired with it as an alternative "installable generator" upgrade.
