### ISSUE TITLE
Support Botania Flower

### ISSUE THREAD

**Issue by tyler489** [mekanism/Mekanism-Feature-Requests#177]
Botania Solegonia is suppost to stop magnets from working in its range however mek suit magnet upgrades bypass this.

**Comment by pupnewfster** [comment]
After previous discussion with people that our magnets bypassed things I went ahead and made it so that we properly support vanilla's no pickup flags. https://github.com/mekanism/Mekanism/commit/d4b425b8b00058a34a39c72e031c0ddf0564f9b5 If botania wants to stop our magnets from picking up said items they should use vanilla's system to mark the items as not being able to be picked up as our magnet basically just extends the range at which the things can be picked up.

**Comment by Hubry** [comment]
The flower doesn't prevent picking up items at all, just makes the magnet ring not do anything if either the player or the item are inside its range. Preventing pickup completely is not the behavior we desire.

**Comment by pupnewfster** [comment]
The concept of magnets is to effectively just extend the range at which things get picked up. Because of how things work we do not want to be doing what previously was suggested to us of doing a ton of NBT checks regarding if the item has some specific tags as that could get somewhat expensive and also not even be fully accurate. If someone makes a forge PR and it gets merged either "extending" vanilla's no pickup to also have a flag type thing for "no magnet" or an entity capability that we can just check if the entity has we would be willing to add support for that in Mekanism. We won't be adding support for some arbitrary NBT flag on the backing stack the item entity is representing though.
