### ISSUE TITLE
[Feature Request] Bin Void Upgrade

### ISSUE THREAD

**Issue by NillerMedDild** [mekanism/Mekanism-Feature-Requests#199]
**Describe the the feature you'd like**
I would like a Void Upgrade for Bins - An item that can be applied to Bins to make them destroy items put into them while they're full.

**Describe alternatives you've considered**
None to be honest :D

**Comment by pupnewfster** [comment]
Moving this to the feature request repo for now, and I will think about it more for 10.1 if maybe it is something "worth" doing and will discuss this with the other members of the team. (Marking it in the 10.1 milestone to remember, though that doesn't mean it will actually be implemented for 10.1)

I am not sure if it *will* happen though, mostly given at least in the past my stance on the matter has been that players should design their factories and the like "properly" so that if their storage is full they aren't just endlessly using up tps by having their machines going just to void the output instead of improving their performance by making it shut down and not be creating things for the sole purpose of deleting them.

What I might be more inclined to consider would be some sort of "incinerator" block that lets you just delete items pumped into it rather than having to rely on dispensers and dumping things into lava that way (which is what I tend to suggest to people if they really want to delete items) and then they could hook their transporter networks up so that it tries to insert into the bin first and if it fails goes on to an incinerator. Though truth be told even with this I personally don't really like the idea of "deleting" items via automation even if it is *sorf of* possible in vanilla.

**Comment by NillerMedDild** [comment]
That's fair, thanks for considering it either way. I do have one comment though:

In the case that the Bins aren't part of automation but simply used as storage, there's no performance incentive to use an incinerator over a void upgrade. It's nice to know the Bin only voids excess, as opposed to having to check how much of a block to keep whenever you dump your inventory into storage after a mining trip.

**Comment by pupnewfster** [comment]
If I were to make an incinerator (which I am also somewhat leaning against), it would mainly be as a way to more automate vanilla's dumping in lava thing, and just as a side effect sort of be able to "act" as a void upgrade (even though yes I agree performance wise that part wouldn't really make a difference).

Though truth be told especially in V10 a void upgrade for bins makes even less sense than it might have in V9, as QIO was designed to be late game item storage as once you get past the early/mid game bins don't really cut it anymore. At which point it would make more sense for players to just upgrade their drives and if they really don't care about their server's performance and stopping generating something when they reach a given amount, they can let their machines keep generating it and then just dump it in their QIO system. Also in a sense given our bins don't have upgrades anyways and instead have tiers there really wouldn't be a clean/logical way to implement a void upgrade.

**Comment by NillerMedDild** [comment]
Good points, I'll just close :)

**Comment by tyler489** [comment]
> Moving this to the feature request repo for now, and I will think about it more for 10.1 if maybe it is something "worth" doing and will discuss this with the other members of the team. (Marking it in the 10.1 milestone to remember, though that doesn't mean it will actually be implemented for 10.1)
> 
> I am not sure if it _will_ happen though, mostly given at least in the past my stance on the matter has been that players should design their factories and the like "properly" so that if their storage is full they aren't just endlessly using up tps by having their machines going just to void the output instead of improving their performance by making it shut down and not be creating things for the sole purpose of deleting them.
> 
> What I might be more inclined to consider would be some sort of "incinerator" block that lets you just delete items pumped into it rather than having to rely on dispensers and dumping things into lava that way (which is what I tend to suggest to people if they really want to delete items) and then they could hook their transporter networks up so that it tries to insert into the bin first and if it fails goes on to an incinerator. Though truth be told even with this I personally don't really like the idea of "deleting" items via automation even if it is _sorf of_ possible in vanilla.

I would just like to say as a server admin I prefer that people have void upgrades on their setup because otherwise something happens and I end up with thousands of items on the ground because no one ever builds any failsafes on their base.... until their setups start to disappear that is.

**Comment by Mr-Manandu** [comment]
I'd like to necro this suggestion to point out a use case.

Supposed you're automating a process that produces X, Y, and Z. In that order of quantity.

I want X, that's the primary goal of the factory and I'm happy to have the factory shut off when the bin is full. I don't want any of Z, but I'd like to keep one bin full of Y and void the rest.

You can achieve this with a priority input system, having it fill Bin Y but also allowing it to send to the void if it's full. But it's a lot easier if I could just whack a void upgrade on Bin Y. Then I could route only Z to the void, send Y to it's bin, and know it won't clog the factory to stop me getting X when it's full, while also not worrying about the system accidentally sending Y to the void before the bin is full.
