### ISSUE TITLE
Why is there no port for minecraft version 1.18.1?

### ISSUE THREAD

**Issue by webmastak** [mekanism/Mekanism-Feature-Requests#395]
### Describe the feature you'd like

Port for minecraft version 1.18.1?

### Additional context

Why is there no port for minecraft version 1.18.1?

**Comment by pupnewfster** [comment]
Mainly because there were some bugs remaining and I initially thought that worlds would not be able to be upgraded from 1.18.1 to 1.18.2, and there is no reason to use 1.18.1 over 1.18.2

**Comment by webmastak** [comment]
The problem is that not all mods have been updated on 1.18.2
You can make a port on 1.18.1 and what is needed for this?
I was looking for a fork for 1.18.1 but did not find it

**Comment by AlexHgC** [comment]
Just update your game. There is really **NO POINT** to play on 1.18.1 because of **minecraft** bugs. Play on 1.18.1 if you want, but d'ont ask mods to update EoL versions juste because you play on EoL version. 

> The problem is that not all mods have been updated on 1.18.2

Well, ask mods to update to 1.18.2 ? And some 1.18.1 mods are compatible with .2 ( so they aren't updated ), try it to see

> You can make a port on 1.18.1 and what is needed for this?

A lot of code change because of how .2 is different. And forge fix/features that aren't updated to .1

> I was looking for a fork for 1.18.1 but did not find it

If you really want to play .1, just play without mek. If you really want mek, play on .2
