### ISSUE TITLE
Minor: Intigration wtih With Wavey capes to disable cape render on HPDE ely and ely upgrade

### ISSUE THREAD

**Issue by Shibva** [mekanism/Mekanism-Feature-Requests#478]
### Describe the feature you'd like

A simple integration to disable the cape render done by Wavy Capes (that replaces the standard cape) when wearing the mods 2 elytra

### Describe alternatives you've considered

none

### Additional context

The mod Wavy Capes is a simple mod that only changes the cape by replacing it with a fancier render that has improved momenet-based orientation and fluid-like motions to that of a real cape

mod is open sourced so this should be a simple integration (I hope)

I also understand that this may be low priority
![image](https://user-images.githubusercontent.com/38770780/198740535-e039e7dd-5321-4d04-8cda-a241ae30f1b2.png)
*in glide with the ely upgrade*

![image](https://user-images.githubusercontent.com/38770780/198740664-782bbd3b-3376-4ddd-bfcc-ba03271299ae.png)

HPDE elytra being worn, model transfer is done as intended but WC cape render is still present

**Comment by Shibva** [comment]
https://github.com/tr7zw/WaveyCapes

When you forget to post the link you were gonna post to the source lol

**Comment by pupnewfster** [comment]
Honestly feels like it is a bug on their end because we specifically set the player's cape to not be visible before rendering the player when it shouldn't be rendered https://github.com/mekanism/Mekanism/blob/1.19.x/src/main/java/mekanism/client/ClientTickHandler.java#L365-L366 https://github.com/mekanism/Mekanism/blob/1.19.x/src/main/java/mekanism/client/ClientTickHandler.java#L355

So if I had to guess they don't check if the cape should be visible or not before rendering it and just always render it instead.

**Comment by pupnewfster** [comment]
Should be fixed from wavy capes' end in 1.2.2 of their mod
