### ISSUE TITLE
Ore Storage block Transmutation support

### ISSUE THREAD

**Issue by Speiger** [mekanism/Mekanism-Feature-Requests#525]
### Describe the feature you'd like

Immersive Engineering has shown me recipes where you can make storage results choseable by the player.
By simply making the Center piece of the Storage recipe hardcoded to the mod this would allow you to choose which output you want.

Personally I think this should be a standard.

Reference issue to show what is wanted. The top recipe shows it clearly
https://github.com/TinyModularThings/IC2Classic/issues/568

**Comment by pupnewfster** [comment]
I will think about this more, but I am still of the belief as I was when IE and a few other tech mods were discussing this a couple years ago that I don't really see much point in this. In theory mods should be using tags for the blocks in their recipes so which one you get/wins the recipe conflict should be irrelevant except for purposes of aesthetic design, but at that point at least with Mekanism you could just use our Oredictionificator to switch between the different types.

Granted I will think about it more given a similar argument could be had that there isn't much of a reason *not* to support it, unless another mod is present that say only provides ingots but does not add a storage block themselves... and then you have to setup two different forms of processing for that ingot in order to make the block variation.

**Comment by Speiger** [comment]
Thank you for the answer.
For your argument:
> another mod is present that say only provides ingots but does not add a storage block themselves...

Technically this still would work, maybe less so, but if you have a few mods that don't have ore compat for example or limited ore compat this would break 1 entire mod just because recipe conflicts exists.

The one example you have is not the ideal solution either.
But the moment you have 1 ingot from another mod you are safe to convert ingots how you like.
While the other way around it blocks all direction unless you have a extra mod installed that from what i have seen doesn't work reliably. (A friend of mine on camera had shown me it works only randomly)

**Comment by pupnewfster** [comment]
Two things:
1. As I think there was a bit of confusion, the Oredictionificator isn't a mod it is a block in Mekanism
2. There is a decent chance I decide to maybe do this just because in the case I mentioned also can just be solved with the oredictionificator as well by just converting the ingots/nuggets to have one for the center type, and thus also allow for the avoiding recipe conflicts as well

**Comment by Speiger** [comment]
1: OH ok, didn't know that, he used a dedicated mod.
2: Yeah that is fine. I just wanted to provide another reason :) The more mods do this the better if this kinda became a standard
