### ISSUE TITLE
Add a pin button to internal tabs in QIO and other interfaces

### ISSUE THREAD

**Issue by notnem** [mekanism/Mekanism-Feature-Requests#571]
### Describe the feature you'd like

A "keep on top" or pin button that can fix windows in place. QIO interface is awful to use as an actual storage system because you need to click to open a crafting table every time, then press escape multiple times to close it then QIO. Pinning the crafting table to the side (or anywhere on the screen, really) would actually make it functional and comparable to AE2.

### Describe alternatives you've considered

There are no alternative solutions. You have to click the button every time to open the crafting table. I suppose the actual solution is installing AE2.

**Comment by AlexHgC** [comment]
I agree 100% with that, can be VERY useful to have "always open" button on crafting/side config/upgrades. I forgot mostly everytime to open crafting windows when using JEI to add recipe, so i have to go back, open it, find again the recipe and add it. 

As the windows save the position since V10.1, a way to pin windows is the next step to get a very good QoL update
