### ISSUE TITLE
Allow radioactive chemicals to enter the condensensator

### ISSUE THREAD

**Issue by screret** [mekanism/Mekanism-Feature-Requests#583]
### Describe the feature you'd like

The Consensensator cannot accept radioactive gases. This is an issue because, for my pack, i need to be able to convert mekanism plutonium to another mod's plutonium fluid, because that mod doesn't have explicit mek compat.

### Describe alternatives you've considered

Adding a gas hatch to GT.
I (and many others) feel like this is a bad solution, and should be avoided.

### Additional context

This is for ATM9's GregTech branch.

**Comment by pupnewfster** [comment]
This will be included for 10.4.0, though I highly recommend to you (or anyone who sees this issue and wants to add conversions themselves) that in addition to adding the recipe you add mekanism's rotary condensentrator to the `forge:relocation_not_supported` Block/BlockEntityType tags so that there is no chance players try to move it when there are radioactive substances in it.

I also will mention as a side note from a balance perspective, allowing it to be converted to other substances (in this case fluids) may lead to players just voiding radioactive stuff via it rather than using appropriate methods to do so.
