### ISSUE TITLE
Port to fabric?

### ISSUE THREAD

**Issue by Ashwinaaaaaaahdt** [mekanism/Mekanism-Feature-Requests#654]
### Describe the feature you'd like

Can you able to port mekanism to fabric
Atleast from version 1.18.2-1.20 latest

**Comment by thiakil** [comment]
From our FAQ on discord:

At this time we have no plans of porting to or supporting Fabric.

Mekanism is MIT licensed, if you want to go ahead and try and port it yourself feel free.

Just keep in mind it is a massive mod that makes use of a lot of Forge features and in no way will be an easy port.

If you do end up porting Mekanism to Fabric, let us know so that we can direct the people who ask to you, and please make it clear via the name that it is unofficial.

**Comment by Ashwinaaaaaaahdt** [comment]
Can you make mod integration with Futurepack
