### ISSUE TITLE
Fission Reactor Port Round-Robin

### ISSUE THREAD

**Issue by SeyfertGames** [mekanism/Mekanism-Feature-Requests#719]
### Describe the feature you'd like

Please make Fission Reactor Ports Round-Robin.

### Describe alternatives you've considered

The only alternative would be to move the boilers right next to the fission reactor.

### Additional context

I have one sodium-cooled fission reactor with two boilers using the Entangled mod to have the ports next to each other. Even though the same Output Coolant port is on both boilers, it only sends the Heated Sodium to 1 Boiler. SuperMartijn642/Entangled#96

**Comment by SeyfertGames** [comment]
If possible, please make other ports for other multiblocks round-robin as well.

**Comment by pupnewfster** [comment]
Uhh, the ports on a reactor already distribute evenly between destinations. I am guessing it only sends to one boiler because they cache the output capability, and I am guessing however entangled works it is only exposing a singular capability?

I am guessing if you used two separate fission ports, and put an entangled boiler input port (one for each boiler) in front of the different fission ports, then it might work as expected?

**Comment by SeyfertGames** [comment]
> Uhh, the ports on a reactor already distribute evenly between destinations. I am guessing it only sends to one boiler because they cache the output capability, and I am guessing however entangled works it is only exposing a singular capability?
> 
> I am guessing if you used two separate fission ports, and put an entangled boiler input port (one for each boiler) in front of the different fission ports, then it might work as expected?

I tried using 2 ports for each boiler, didn't work.

**Comment by pupnewfster** [comment]
What version of MC are you on?

**Comment by SeyfertGames** [comment]
> What version of MC are you on?

1.20.1

**Comment by pupnewfster** [comment]
Ah, that would be why. It wasn't until 1.20.4 that we made that change https://github.com/mekanism/Mekanism/commit/16b356547c1305c0668ee3e7cd5d1512dfb3b377

Going to close this as it has been implemented in newer versions
